insert into continent(code,name) values
('AF', 'Africa'),
  ('AS', 'Asia'),
  ('EU', 'Europe'),
  ('NA', 'North America'),
  ('SA', 'South America'),
  ('OC', 'Oceania'),
  ('AN', 'Antarctica');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AF', 'AS', 'Afghanistan', 'AFG', '004', 'Islamic Republic of Afghanistan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AX', 'EU', 'Åland Islands', 'ALA', '248', 'Åland Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AL', 'EU', 'Albania', 'ALB', '008', 'Republic of Albania');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('DZ', 'AF', 'Algeria', 'DZA', '012', 'People''s Democratic Republic of Algeria');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AS', 'OC', 'American Samoa', 'ASM', '016', 'American Samoa');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AD', 'EU', 'Andorra', 'AND', '020', 'Principality of Andorra');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AO', 'AF', 'Angola', 'AGO', '024', 'Republic of Angola');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AI', 'NA', 'Anguilla', 'AIA', '660', 'Anguilla');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AQ', 'AN', 'Antarctica', 'ATA', '010', 'Antarctica (the territory South of 60 deg S)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AG', 'NA', 'Antigua and Barbuda', 'ATG', '028', 'Antigua and Barbuda');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AR', 'SA', 'Argentina', 'ARG', '032', 'Argentine Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AM', 'AS', 'Armenia', 'ARM', '051', 'Republic of Armenia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AW', 'NA', 'Aruba', 'ABW', '533', 'Aruba');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AU', 'OC', 'Australia', 'AUS', '036', 'Commonwealth of Australia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AT', 'EU', 'Austria', 'AUT', '040', 'Republic of Austria');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AZ', 'AS', 'Azerbaijan', 'AZE', '031', 'Republic of Azerbaijan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BS', 'NA', 'Bahamas', 'BHS', '044', 'Commonwealth of the Bahamas');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BH', 'AS', 'Bahrain', 'BHR', '048', 'Kingdom of Bahrain');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BD', 'AS', 'Bangladesh', 'BGD', '050', 'People''s Republic of Bangladesh');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BB', 'NA', 'Barbados', 'BRB', '052', 'Barbados');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BY', 'EU', 'Belarus', 'BLR', '112', 'Republic of Belarus');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BE', 'EU', 'Belgium', 'BEL', '056', 'Kingdom of Belgium');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BZ', 'NA', 'Belize', 'BLZ', '084', 'Belize');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BJ', 'AF', 'Benin', 'BEN', '204', 'Republic of Benin');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BM', 'NA', 'Bermuda', 'BMU', '060', 'Bermuda');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BT', 'AS', 'Bhutan', 'BTN', '064', 'Kingdom of Bhutan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BO', 'SA', 'Bolivia', 'BOL', '068', 'Plurinational State of Bolivia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BQ', 'NA', 'Bonaire, Sint Eustatius and Saba', 'BES', '535', 'Bonaire, Sint Eustatius and Saba');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BA', 'EU', 'Bosnia and Herzegovina', 'BIH', '070', 'Bosnia and Herzegovina');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BW', 'AF', 'Botswana', 'BWA', '072', 'Republic of Botswana');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BV', 'AN', 'Bouvet Island (Bouvetoya)', 'BVT', '074', 'Bouvet Island (Bouvetoya)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BR', 'SA', 'Brazil', 'BRA', '076', 'Federative Republic of Brazil');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IO', 'AS', 'British Indian Ocean Territory (Chagos Archipelago)', 'IOT', '086', 'British Indian Ocean Territory (Chagos Archipelago)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('VG', 'NA', 'British Virgin Islands', 'VGB', '092', 'British Virgin Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BN', 'AS', 'Brunei Darussalam', 'BRN', '096', 'Brunei Darussalam');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BG', 'EU', 'Bulgaria', 'BGR', '100', 'Republic of Bulgaria');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BF', 'AF', 'Burkina Faso', 'BFA', '854', 'Burkina Faso');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BI', 'AF', 'Burundi', 'BDI', '108', 'Republic of Burundi');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KH', 'AS', 'Cambodia', 'KHM', '116', 'Kingdom of Cambodia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CM', 'AF', 'Cameroon', 'CMR', '120', 'Republic of Cameroon');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CA', 'NA', 'Canada', 'CAN', '124', 'Canada');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CV', 'AF', 'Cape Verde', 'CPV', '132', 'Republic of Cape Verde');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KY', 'NA', 'Cayman Islands', 'CYM', '136', 'Cayman Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CF', 'AF', 'Central African Republic', 'CAF', '140', 'Central African Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TD', 'AF', 'Chad', 'TCD', '148', 'Republic of Chad');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CL', 'SA', 'Chile', 'CHL', '152', 'Republic of Chile');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CN', 'AS', 'China', 'CHN', '156', 'People''s Republic of China');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CX', 'AS', 'Christmas Island', 'CXR', '162', 'Christmas Island');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CC', 'AS', 'Cocos (Keeling) Islands', 'CCK', '166', 'Cocos (Keeling) Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CO', 'SA', 'Colombia', 'COL', '170', 'Republic of Colombia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KM', 'AF', 'Comoros', 'COM', '174', 'Union of the Comoros');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CD', 'AF', 'Congo', 'COD', '180', 'Democratic Republic of the Congo');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CG', 'AF', 'Congo', 'COG', '178', 'Republic of the Congo');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CK', 'OC', 'Cook Islands', 'COK', '184', 'Cook Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CR', 'NA', 'Costa Rica', 'CRI', '188', 'Republic of Costa Rica');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CI', 'AF', 'Cote d''Ivoire', 'CIV', '384', 'Republic of Cote d''Ivoire');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('HR', 'EU', 'Croatia', 'HRV', '191', 'Republic of Croatia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CU', 'NA', 'Cuba', 'CUB', '192', 'Republic of Cuba');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CW', 'NA', 'Curaçao', 'CUW', '531', 'Curaçao');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CY', 'AS', 'Cyprus', 'CYP', '196', 'Republic of Cyprus');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CZ', 'EU', 'Czech Republic', 'CZE', '203', 'Czech Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('DK', 'EU', 'Denmark', 'DNK', '208', 'Kingdom of Denmark');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('DJ', 'AF', 'Djibouti', 'DJI', '262', 'Republic of Djibouti');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('DM', 'NA', 'Dominica', 'DMA', '212', 'Commonwealth of Dominica');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('DO', 'NA', 'Dominican Republic', 'DOM', '214', 'Dominican Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('EC', 'SA', 'Ecuador', 'ECU', '218', 'Republic of Ecuador');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('EG', 'AF', 'Egypt', 'EGY', '818', 'Arab Republic of Egypt');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SV', 'NA', 'El Salvador', 'SLV', '222', 'Republic of El Salvador');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GQ', 'AF', 'Equatorial Guinea', 'GNQ', '226', 'Republic of Equatorial Guinea');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ER', 'AF', 'Eritrea', 'ERI', '232', 'State of Eritrea');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('EE', 'EU', 'Estonia', 'EST', '233', 'Republic of Estonia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ET', 'AF', 'Ethiopia', 'ETH', '231', 'Federal Democratic Republic of Ethiopia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('FO', 'EU', 'Faroe Islands', 'FRO', '234', 'Faroe Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('FK', 'SA', 'Falkland Islands (Malvinas)', 'FLK', '238', 'Falkland Islands (Malvinas)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('FJ', 'OC', 'Fiji', 'FJI', '242', 'Republic of Fiji');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('FI', 'EU', 'Finland', 'FIN', '246', 'Republic of Finland');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('FR', 'EU', 'France', 'FRA', '250', 'French Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GF', 'SA', 'French Guiana', 'GUF', '254', 'French Guiana');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PF', 'OC', 'French Polynesia', 'PYF', '258', 'French Polynesia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TF', 'AN', 'French Southern Territories', 'ATF', '260', 'French Southern Territories');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GA', 'AF', 'Gabon', 'GAB', '266', 'Gabonese Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GM', 'AF', 'Gambia', 'GMB', '270', 'Republic of the Gambia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GE', 'AS', 'Georgia', 'GEO', '268', 'Georgia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('DE', 'EU', 'Germany', 'DEU', '276', 'Federal Republic of Germany');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GH', 'AF', 'Ghana', 'GHA', '288', 'Republic of Ghana');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GI', 'EU', 'Gibraltar', 'GIB', '292', 'Gibraltar');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GR', 'EU', 'Greece', 'GRC', '300', 'Hellenic Republic Greece');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GL', 'NA', 'Greenland', 'GRL', '304', 'Greenland');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GD', 'NA', 'Grenada', 'GRD', '308', 'Grenada');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GP', 'NA', 'Guadeloupe', 'GLP', '312', 'Guadeloupe');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GU', 'OC', 'Guam', 'GUM', '316', 'Guam');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GT', 'NA', 'Guatemala', 'GTM', '320', 'Republic of Guatemala');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GG', 'EU', 'Guernsey', 'GGY', '831', 'Bailiwick of Guernsey');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GN', 'AF', 'Guinea', 'GIN', '324', 'Republic of Guinea');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GW', 'AF', 'Guinea-Bissau', 'GNB', '624', 'Republic of Guinea-Bissau');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GY', 'SA', 'Guyana', 'GUY', '328', 'Co-operative Republic of Guyana');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('HT', 'NA', 'Haiti', 'HTI', '332', 'Republic of Haiti');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('HM', 'AN', 'Heard Island and McDonald Islands', 'HMD', '334', 'Heard Island and McDonald Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('VA', 'EU', 'Holy See (Vatican City State)', 'VAT', '336', 'Holy See (Vatican City State)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('HN', 'NA', 'Honduras', 'HND', '340', 'Republic of Honduras');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('HK', 'AS', 'Hong Kong', 'HKG', '344', 'Hong Kong Special Administrative Region of China');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('HU', 'EU', 'Hungary', 'HUN', '348', 'Hungary');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IS', 'EU', 'Iceland', 'ISL', '352', 'Republic of Iceland');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IN', 'AS', 'India', 'IND', '356', 'Republic of India');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ID', 'AS', 'Indonesia', 'IDN', '360', 'Republic of Indonesia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IR', 'AS', 'Iran', 'IRN', '364', 'Islamic Republic of Iran');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IQ', 'AS', 'Iraq', 'IRQ', '368', 'Republic of Iraq');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IE', 'EU', 'Ireland', 'IRL', '372', 'Ireland');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IM', 'EU', 'Isle of Man', 'IMN', '833', 'Isle of Man');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IL', 'AS', 'Israel', 'ISR', '376', 'State of Israel');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('IT', 'EU', 'Italy', 'ITA', '380', 'Italian Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('JM', 'NA', 'Jamaica', 'JAM', '388', 'Jamaica');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('JP', 'AS', 'Japan', 'JPN', '392', 'Japan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('JE', 'EU', 'Jersey', 'JEY', '832', 'Bailiwick of Jersey');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('JO', 'AS', 'Jordan', 'JOR', '400', 'Hashemite Kingdom of Jordan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KZ', 'AS', 'Kazakhstan', 'KAZ', '398', 'Republic of Kazakhstan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KE', 'AF', 'Kenya', 'KEN', '404', 'Republic of Kenya');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KI', 'OC', 'Kiribati', 'KIR', '296', 'Republic of Kiribati');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KP', 'AS', 'Korea', 'PRK', '408', 'Democratic People''s Republic of Korea');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KR', 'AS', 'Korea', 'KOR', '410', 'Republic of Korea');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KW', 'AS', 'Kuwait', 'KWT', '414', 'State of Kuwait');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KG', 'AS', 'Kyrgyz Republic', 'KGZ', '417', 'Kyrgyz Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LA', 'AS', 'Lao People''s Democratic Republic', 'LAO', '418', 'Lao People''s Democratic Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LV', 'EU', 'Latvia', 'LVA', '428', 'Republic of Latvia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LB', 'AS', 'Lebanon', 'LBN', '422', 'Lebanese Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LS', 'AF', 'Lesotho', 'LSO', '426', 'Kingdom of Lesotho');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LR', 'AF', 'Liberia', 'LBR', '430', 'Republic of Liberia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LY', 'AF', 'Libya', 'LBY', '434', 'Libya');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LI', 'EU', 'Liechtenstein', 'LIE', '438', 'Principality of Liechtenstein');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LT', 'EU', 'Lithuania', 'LTU', '440', 'Republic of Lithuania');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LU', 'EU', 'Luxembourg', 'LUX', '442', 'Grand Duchy of Luxembourg');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MO', 'AS', 'Macao', 'MAC', '446', 'Macao Special Administrative Region of China');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MK', 'EU', 'Macedonia', 'MKD', '807', 'Republic of Macedonia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MG', 'AF', 'Madagascar', 'MDG', '450', 'Republic of Madagascar');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MW', 'AF', 'Malawi', 'MWI', '454', 'Republic of Malawi');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MY', 'AS', 'Malaysia', 'MYS', '458', 'Malaysia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MV', 'AS', 'Maldives', 'MDV', '462', 'Republic of Maldives');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ML', 'AF', 'Mali', 'MLI', '466', 'Republic of Mali');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MT', 'EU', 'Malta', 'MLT', '470', 'Republic of Malta');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MH', 'OC', 'Marshall Islands', 'MHL', '584', 'Republic of the Marshall Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MQ', 'NA', 'Martinique', 'MTQ', '474', 'Martinique');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MR', 'AF', 'Mauritania', 'MRT', '478', 'Islamic Republic of Mauritania');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MU', 'AF', 'Mauritius', 'MUS', '480', 'Republic of Mauritius');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('YT', 'AF', 'Mayotte', 'MYT', '175', 'Mayotte');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MX', 'NA', 'Mexico', 'MEX', '484', 'United Mexican States');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('FM', 'OC', 'Micronesia', 'FSM', '583', 'Federated States of Micronesia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MD', 'EU', 'Moldova', 'MDA', '498', 'Republic of Moldova');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MC', 'EU', 'Monaco', 'MCO', '492', 'Principality of Monaco');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MN', 'AS', 'Mongolia', 'MNG', '496', 'Mongolia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ME', 'EU', 'Montenegro', 'MNE', '499', 'Montenegro');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MS', 'NA', 'Montserrat', 'MSR', '500', 'Montserrat');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MA', 'AF', 'Morocco', 'MAR', '504', 'Kingdom of Morocco');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MZ', 'AF', 'Mozambique', 'MOZ', '508', 'Republic of Mozambique');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MM', 'AS', 'Myanmar', 'MMR', '104', 'Republic of the Union of Myanmar');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NA', 'AF', 'Namibia', 'NAM', '516', 'Republic of Namibia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NR', 'OC', 'Nauru', 'NRU', '520', 'Republic of Nauru');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NP', 'AS', 'Nepal', 'NPL', '524', 'Federal Democratic Republic of Nepal');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NL', 'EU', 'Netherlands', 'NLD', '528', 'Kingdom of the Netherlands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NC', 'OC', 'New Caledonia', 'NCL', '540', 'New Caledonia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NZ', 'OC', 'New Zealand', 'NZL', '554', 'New Zealand');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NI', 'NA', 'Nicaragua', 'NIC', '558', 'Republic of Nicaragua');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NE', 'AF', 'Niger', 'NER', '562', 'Republic of Niger');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NG', 'AF', 'Nigeria', 'NGA', '566', 'Federal Republic of Nigeria');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NU', 'OC', 'Niue', 'NIU', '570', 'Niue');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NF', 'OC', 'Norfolk Island', 'NFK', '574', 'Norfolk Island');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MP', 'OC', 'Northern Mariana Islands', 'MNP', '580', 'Commonwealth of the Northern Mariana Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('NO', 'EU', 'Norway', 'NOR', '578', 'Kingdom of Norway');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('OM', 'AS', 'Oman', 'OMN', '512', 'Sultanate of Oman');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PK', 'AS', 'Pakistan', 'PAK', '586', 'Islamic Republic of Pakistan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PW', 'OC', 'Palau', 'PLW', '585', 'Republic of Palau');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PS', 'AS', 'Palestinian Territory', 'PSE', '275', 'Occupied Palestinian Territory');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PA', 'NA', 'Panama', 'PAN', '591', 'Republic of Panama');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PG', 'OC', 'Papua New Guinea', 'PNG', '598', 'Independent State of Papua New Guinea');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PY', 'SA', 'Paraguay', 'PRY', '600', 'Republic of Paraguay');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PE', 'SA', 'Peru', 'PER', '604', 'Republic of Peru');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PH', 'AS', 'Philippines', 'PHL', '608', 'Republic of the Philippines');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PN', 'OC', 'Pitcairn Islands', 'PCN', '612', 'Pitcairn Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PL', 'EU', 'Poland', 'POL', '616', 'Republic of Poland');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PT', 'EU', 'Portugal', 'PRT', '620', 'Portuguese Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PR', 'NA', 'Puerto Rico', 'PRI', '630', 'Commonwealth of Puerto Rico');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('QA', 'AS', 'Qatar', 'QAT', '634', 'State of Qatar');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('RE', 'AF', 'Réunion', 'REU', '638', 'Réunion');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('RO', 'EU', 'Romania', 'ROU', '642', 'Romania');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('RU', 'EU', 'Russian Federation', 'RUS', '643', 'Russian Federation');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('RW', 'AF', 'Rwanda', 'RWA', '646', 'Republic of Rwanda');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('BL', 'NA', 'Saint Barthélemy', 'BLM', '652', 'Saint Barthélemy');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SH', 'AF', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('KN', 'NA', 'Saint Kitts and Nevis', 'KNA', '659', 'Federation of Saint Kitts and Nevis');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LC', 'NA', 'Saint Lucia', 'LCA', '662', 'Saint Lucia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('MF', 'NA', 'Saint Martin', 'MAF', '663', 'Saint Martin (French part)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('PM', 'NA', 'Saint Pierre and Miquelon', 'SPM', '666', 'Saint Pierre and Miquelon');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('VC', 'NA', 'Saint Vincent and the Grenadines', 'VCT', '670', 'Saint Vincent and the Grenadines');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('WS', 'OC', 'Samoa', 'WSM', '882', 'Independent State of Samoa');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SM', 'EU', 'San Marino', 'SMR', '674', 'Republic of San Marino');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ST', 'AF', 'Sao Tome and Principe', 'STP', '678', 'Democratic Republic of Sao Tome and Principe');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SA', 'AS', 'Saudi Arabia', 'SAU', '682', 'Kingdom of Saudi Arabia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SN', 'AF', 'Senegal', 'SEN', '686', 'Republic of Senegal');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('RS', 'EU', 'Serbia', 'SRB', '688', 'Republic of Serbia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SC', 'AF', 'Seychelles', 'SYC', '690', 'Republic of Seychelles');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SL', 'AF', 'Sierra Leone', 'SLE', '694', 'Republic of Sierra Leone');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SG', 'AS', 'Singapore', 'SGP', '702', 'Republic of Singapore');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SX', 'NA', 'Sint Maarten (Dutch part)', 'SXM', '534', 'Sint Maarten (Dutch part)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SK', 'EU', 'Slovakia (Slovak Republic)', 'SVK', '703', 'Slovakia (Slovak Republic)');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SI', 'EU', 'Slovenia', 'SVN', '705', 'Republic of Slovenia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SB', 'OC', 'Solomon Islands', 'SLB', '090', 'Solomon Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SO', 'AF', 'Somalia', 'SOM', '706', 'Somali Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ZA', 'AF', 'South Africa', 'ZAF', '710', 'Republic of South Africa');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GS', 'AN', 'South Georgia and the South Sandwich Islands', 'SGS', '239', 'South Georgia and the South Sandwich Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SS', 'AF', 'South Sudan', 'SSD', '728', 'Republic of South Sudan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ES', 'EU', 'Spain', 'ESP', '724', 'Kingdom of Spain');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('LK', 'AS', 'Sri Lanka', 'LKA', '144', 'Democratic Socialist Republic of Sri Lanka');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SD', 'AF', 'Sudan', 'SDN', '729', 'Republic of Sudan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SR', 'SA', 'Suriname', 'SUR', '740', 'Republic of Suriname');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SJ', 'EU', 'Svalbard & Jan Mayen Islands', 'SJM', '744', 'Svalbard & Jan Mayen Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SZ', 'AF', 'Swaziland', 'SWZ', '748', 'Kingdom of Swaziland');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SE', 'EU', 'Sweden', 'SWE', '752', 'Kingdom of Sweden');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('CH', 'EU', 'Switzerland', 'CHE', '756', 'Swiss Confederation');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('SY', 'AS', 'Syrian Arab Republic', 'SYR', '760', 'Syrian Arab Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TW', 'AS', 'Taiwan', 'TWN', '158', 'Taiwan, Province of China');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TJ', 'AS', 'Tajikistan', 'TJK', '762', 'Republic of Tajikistan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TZ', 'AF', 'Tanzania', 'TZA', '834', 'United Republic of Tanzania');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TH', 'AS', 'Thailand', 'THA', '764', 'Kingdom of Thailand');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TL', 'AS', 'Timor-Leste', 'TLS', '626', 'Democratic Republic of Timor-Leste');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TG', 'AF', 'Togo', 'TGO', '768', 'Togolese Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TK', 'OC', 'Tokelau', 'TKL', '772', 'Tokelau');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TO', 'OC', 'Tonga', 'TON', '776', 'Kingdom of Tonga');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TT', 'NA', 'Trinidad and Tobago', 'TTO', '780', 'Republic of Trinidad and Tobago');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TN', 'AF', 'Tunisia', 'TUN', '788', 'Tunisian Republic');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TR', 'AS', 'Turkey', 'TUR', '792', 'Republic of Turkey');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TM', 'AS', 'Turkmenistan', 'TKM', '795', 'Turkmenistan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TC', 'NA', 'Turks and Caicos Islands', 'TCA', '796', 'Turks and Caicos Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('TV', 'OC', 'Tuvalu', 'TUV', '798', 'Tuvalu');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('UG', 'AF', 'Uganda', 'UGA', '800', 'Republic of Uganda');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('UA', 'EU', 'Ukraine', 'UKR', '804', 'Ukraine');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('AE', 'AS', 'United Arab Emirates', 'ARE', '784', 'United Arab Emirates');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('GB', 'EU', 'United Kingdom of Great Britain & Northern Ireland', 'GBR', '826', 'United Kingdom of Great Britain & Northern Ireland');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('US', 'NA', 'United States of America', 'USA', '840', 'United States of America');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('UM', 'OC', 'United States Minor Outlying Islands', 'UMI', '581', 'United States Minor Outlying Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('VI', 'NA', 'United States Virgin Islands', 'VIR', '850', 'United States Virgin Islands');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('UY', 'SA', 'Uruguay', 'URY', '858', 'Eastern Republic of Uruguay');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('UZ', 'AS', 'Uzbekistan', 'UZB', '860', 'Republic of Uzbekistan');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('VU', 'OC', 'Vanuatu', 'VUT', '548', 'Republic of Vanuatu');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('VE', 'SA', 'Venezuela', 'VEN', '862', 'Bolivarian Republic of Venezuela');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('VN', 'AS', 'Vietnam', 'VNM', '704', 'Socialist Republic of Vietnam');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('WF', 'OC', 'Wallis and Futuna', 'WLF', '876', 'Wallis and Futuna');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('EH', 'AF', 'Western Sahara', 'ESH', '732', 'Western Sahara');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('YE', 'AS', 'Yemen', 'YEM', '887', 'Yemen');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ZM', 'AF', 'Zambia', 'ZMB', '894', 'Republic of Zambia');
  INSERT INTO country (code, continent_code, name, iso3, number, full_name) VALUES('ZW', 'AF', 'Zimbabwe', 'ZWE', '716', 'Republic of Zimbabwe');
  
